# PyTorch Tensor

## Tensor의 기본 개념

PyTorch의 `torch.Tensor`는 다차원 배열을 표현하는 핵심 클래스입니다. 객체 지향 프로그래밍의 관점에서 `Tensor`는 명확한 클래스이며, 데이터와 그 데이터를 처리하는 메서드를 함께 캡슐화합니다. NumPy의 ndarray와 유사하지만 GPU 가속과 자동 미분(Autograd) 기능이 추가되어 딥러닝 연산에 최적화되어 있습니다.

```python
import torch

# Tensor 클래스의 인스턴스 생성
x = torch.Tensor([1, 2, 3])
print(type(x))  # 출력: <class 'torch.Tensor'>

# 또는 torch.tensor 함수를 사용 (소문자 t)
y = torch.tensor([1, 2, 3])
print(type(y))  # 출력: <class 'torch.Tensor'>

# 클래스 확인
print(isinstance(x, torch.Tensor))  # 출력: True
```


## Tensor 클래스의 구조

PyTorch에서 `torch.Tensor`는 실제로 여러 구체적인 텐서 타입의 기본 클래스입니다. 데이터 타입에 따라 다양한 구체적인 텐서 클래스가 있습니다:

- `torch.FloatTensor` (기본값)
- `torch.DoubleTensor`
- `torch.IntTensor`
- `torch.LongTensor`
- 등...

그러나 일반적으로 개발자는 이러한 구체적인 클래스를 직접 사용하기보다는 `torch.Tensor` 또는 `torch.tensor()` 함수를 통해 텐서를 생성합니다.

```python
# 클래스 확인
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(type(x))  # <class 'torch.Tensor'>
print(x.__class__)  # <class 'torch.Tensor'>

# 상속 관계 확인
print(torch.Tensor.__mro__)  # 메서드 해결 순서 (Method Resolution Order) 출력
```


## Tensor의 주요 특징

1. **다차원 배열**: 스칼라(0차원), 벡터(1차원), 행렬(2차원), 그리고 더 높은 차원의 데이터 표현 가능
2. **GPU 가속**: CUDA 지원 GPU에서 실행 가능하여 계산 속도 향상
3. **자동 미분**: 역전파를 위한 그래디언트 계산을 자동으로 처리
4. **NumPy와의 호환성**: NumPy 배열과 쉽게 변환 가능
5. **클래스 기반**: 데이터와 연산을 캡슐화한 객체 지향적 설계

## Tensor 생성 방법

```python
# 직접 데이터로부터 생성
x = torch.tensor([1, 2, 3])

# 특정 크기의 0으로 채워진 텐서
zeros = torch.zeros(2, 3)

# 특정 크기의 1로 채워진 텐서
ones = torch.ones(2, 3)

# 임의의 값으로 초기화
random = torch.rand(2, 3)

# NumPy 배열에서 변환
import numpy as np
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
```


## Tensor의 속성과 메서드

클래스로서의 Tensor는 다양한 속성(attributes)과 메서드(methods)를 제공합니다:

```python
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 텐서의 속성
print(x.dim())     # 차원 수: 2
print(x.shape)     # 크기: torch.Size([2, 3])
print(x.size())    # 크기: torch.Size([2, 3])
print(x.dtype)     # 데이터 타입: torch.int64
print(x.device)    # 저장된 장치: cpu
print(x.requires_grad)  # 그래디언트 계산 여부: False

# 텐서의 메서드
print(x.sum())     # 합계: tensor(21)
print(x.mean())    # 평균: tensor(3.5000)
print(x.max())     # 최대값: tensor(6)
print(x.argmax())  # 최대값의 인덱스: tensor(5)
```


## 클래스 메서드와 연산자 오버로딩

Tensor 클래스는 연산자 오버로딩을 통해 직관적인 수학 연산을 지원합니다:

```python
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 연산자 오버로딩을 통한 연산
print(a + b)  # 덧셈: tensor([5, 7, 9])
print(a - b)  # 뺄셈: tensor([-3, -3, -3])
print(a * b)  # 원소별 곱셈: tensor([4, 10, 18])
print(a / b)  # 원소별 나눗셈: tensor([0.2500, 0.4000, 0.5000])

# 내장 메서드 사용
print(torch.add(a, b))      # 덧셈
print(torch.mul(a, b))      # 원소별 곱셈
print(torch.matmul(a, b))   # 내적: tensor(32)

# 인스턴스 메서드 사용
print(a.add(b))      # 덧셈
print(a.mul(b))      # 원소별 곱셈
print(a.matmul(b))   # 내적

# 인플레이스 메서드 (언더스코어로 끝나는 메서드)
c = a.clone()  # a의 복사본 생성
c.add_(b)      # c = c + b, c는 이제 tensor([5, 7, 9])
```


## 텐서 재구성 및 인덱싱

```python
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 재구성 메서드
y = x.view(3, 2)    # 크기 변경
z = x.reshape(3, 2)  # 크기 변경 (복사본 생성 가능)

# 인덱싱
print(x[0])         # 첫 번째 행: tensor([1, 2, 3])
print(x[:, 1])      # 두 번째 열: tensor([2, 5])
print(x[0, 2])      # 첫 번째 행, 세 번째 열의 요소: tensor(3)
```


## 장치 간 텐서 이동

```python
# CPU에 텐서 생성
x = torch.tensor([1, 2, 3])

# GPU로 이동 (GPU가 있는 경우)
if torch.cuda.is_available():
    device = torch.device("cuda")
    x_gpu = x.to(device)  # to 메서드 사용
    # 또는
    x_gpu = x.cuda()  # cuda 메서드 사용

    # CPU로 다시 이동
    x_cpu = x_gpu.cpu()  # cpu 메서드 사용
```


## 자동 미분 (Autograd)

```python
# 그래디언트 계산을 위해 requires_grad=True 설정
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2
y.backward()  # backward 메서드 호출

# 그래디언트 확인 (grad 속성)
print(x.grad)  # 출력: tensor([4.])
```


## NumPy와 Tensor의 공통점과 차이점

### 공통점

1. **다차원 배열 표현**: 두 라이브러리 모두 다차원 배열을 효율적으로 처리
2. **벡터화 연산**: 루프 없이 배열 전체에 대한 연산 지원
3. **브로드캐스팅**: 크기가 다른 배열 간의 연산 자동 조정
4. **인덱싱과 슬라이싱**: 유사한 방식의 데이터 접근 메커니즘
5. **선형 대수 연산**: 행렬 곱셈, 전치 등 유사한 선형 대수 연산 지원

### 차이점

1. **클래스 구조**: PyTorch의 Tensor는 명확한 클래스이며, NumPy의 ndarray도 클래스지만 API 설계 철학이 다름
2. **자동 미분**: PyTorch Tensor는 자동 미분을 지원하지만 NumPy는 지원하지 않음
3. **GPU 가속**: PyTorch는 GPU에서 연산 가능, NumPy는 기본적으로 CPU에서만 동작
4. **인플레이스 연산 표기법**: PyTorch는 인플레이스 연산에 언더스코어(_)를 사용
5. **연산 실행 시점**: PyTorch는 즉시 실행(eager execution)과 지연 실행(deferred execution) 모두 지원
6. **메모리 관리**: PyTorch는 CUDA 메모리 관리를 포함한 더 복잡한 메모리 관리 기능 제공

## NumPy와 PyTorch 함수의 대응 관계

| NumPy 함수 | PyTorch 함수 | 설명 |
|------------|--------------|------|
| `np.array()` | `torch.tensor()` | 배열/텐서 생성 |
| `np.zeros()` | `torch.zeros()` | 0으로 채워진 배열/텐서 생성 |
| `np.ones()` | `torch.ones()` | 1로 채워진 배열/텐서 생성 |
| `np.random.rand()` | `torch.rand()` | 균등 분포의 난수 생성 |
| `np.random.randn()` | `torch.randn()` | 정규 분포의 난수 생성 |
| `np.eye()` | `torch.eye()` | 단위 행렬 생성 |
| `np.dot()` | `torch.matmul()`, `torch.mm()` | 행렬 곱셈 |
| `arr.reshape()` | `tensor.view()`, `tensor.reshape()` | 배열/텐서 재구성 |
| `arr.transpose()` | `tensor.t()`, `tensor.transpose()` | 전치 |
| `np.sum()` | `torch.sum()` | 합계 계산 |
| `np.mean()` | `torch.mean()` | 평균 계산 |
| `np.max()` | `torch.max()` | 최대값 계산 |
| `np.argmax()` | `torch.argmax()` | 최대값의 인덱스 |
| `np.concatenate()` | `torch.cat()` | 배열/텐서 연결 |
| `np.stack()` | `torch.stack()` | 배열/텐서 쌓기 |
| `np.split()` | `torch.split()` | 배열/텐서 분할 |
| `np.where()` | `torch.where()` | 조건에 따른 값 선택 |
| `np.exp()` | `torch.exp()` | 지수 함수 |
| `np.log()` | `torch.log()` | 로그 함수 |
| `np.sin()` | `torch.sin()` | 사인 함수 |

## NumPy와 Tensor 간 변환

```python
# Tensor -> NumPy
tensor = torch.ones(3)
numpy_array = tensor.numpy()  # numpy 메서드 사용
# tensor가 GPU에 있다면 먼저 CPU로 이동해야 함
# numpy_array = tensor.cpu().numpy()

# NumPy -> Tensor
numpy_array = np.ones(3)
tensor = torch.from_numpy(numpy_array)  # NumPy 배열과 메모리 공유
# 또는
tensor = torch.tensor(numpy_array)  # 복사본 생성
```


## 주의사항

1. **메모리 공유**: `torch.from_numpy()`를 사용하면 NumPy 배열과 Tensor가 메모리를 공유하므로 한쪽의 변경이 다른 쪽에도 반영됨
2. **데이터 타입**: NumPy와 PyTorch의 데이터 타입이 정확히 일치하지 않을 수 있으므로 변환 시 주의 필요
3. **인플레이스 연산**: PyTorch에서는 인플레이스 연산이 메모리 효율성을 높이지만, 자동 미분 그래프에 문제를 일으킬 수 있음
4. **GPU 텐서**: GPU에 있는 텐서는 NumPy로 직접 변환할 수 없으며, 먼저 CPU로 이동해야 함
5. **메서드 체이닝**: Tensor는 클래스이므로 메서드 체이닝을 통해 연산을 연속적으로 수행할 수 있음

PyTorch의 Tensor는 명확한 클래스 구조를 가지고 있으며, NumPy의 ndarray를 기반으로 설계되었지만 딥러닝에 최적화된 추가 기능을 제공합니다. 객체 지향 프로그래밍의 개념을 따르며, 데이터와 그 데이터를 처리하는 메서드를 함께 캡슐화하여 직관적이고 표현력 있는 코드를 작성할 수 있게 합니다. 두 라이브러리 간의 쉬운 변환과 유사한 API 덕분에 NumPy에 익숙한 사용자는 PyTorch로 쉽게 전환할 수 있습니다.

In [1]:
import torch

In [2]:
# uniform distribution 에서 random 하게 값을 뽑아, (2, 3) shape 으로 만들어줌
torch.rand(2, 3)

tensor([[0.5110, 0.2146, 0.3671],
        [0.3012, 0.3319, 0.8225]])

In [3]:
# 표준 정규 분포에서 random 하게 값을 뽑아, (2, 3) shape 으로 만들어줌
torch.randn(2, 3)

tensor([[ 0.4482, -0.3691, -0.8133],
        [ 0.0045, -0.3568,  1.0619]])

In [4]:
# 0 <= x < 10 사이에서 random 하게 정수값을 뽑아(2, 3) shape 으로 만들어줌
torch.randint(0, 10, (2, 3))

tensor([[8, 0, 2],
        [8, 2, 8]])

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.full((2, 3), 42)

tensor([[42, 42, 42],
        [42, 42, 42]])

In [8]:
torch.eye(2, 3)  # 2차원 단위 행렬 생성

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [9]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.tensor(tuple(((1, 2, 3), (4, 5, 6))))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
import numpy as np


torch.tensor(np.array(np.array([1, 2, 3])))

tensor([1, 2, 3])

## torch.from_numpy 와 torch.as_tensor 비교

`torch.from_numpy`와 `torch.as_tensor` 함수는 모두 NumPy 배열을 PyTorch 텐서로 변환하는 데 사용되지만, 메모리 관리와 데이터 공유 방식에서 중요한 차이점이 있습니다.

### 공통점

1. **NumPy에서 PyTorch로 변환**: 두 함수 모두 NumPy 배열을 PyTorch 텐서로 변환합니다.
2. **메모리 공유 가능**: 두 함수 모두 특정 조건에서 원본 NumPy 배열과 메모리를 공유합니다.
3. **기본 데이터 타입 유지**: 변환 시 원본 데이터의 타입을 기본적으로 유지합니다.

### 차이점

#### 1. 입력 데이터 유형

- **torch.from_numpy**:
  - **오직 NumPy 배열만** 입력으로 받습니다.
  - 다른 유형의 데이터(리스트, 파이썬 배열 등)는 받지 않습니다.

- **torch.as_tensor**:
  - **다양한 데이터 유형**을 처리할 수 있습니다 (NumPy 배열, 파이썬 리스트, 스칼라 값 등).
  - 이미 PyTorch 텐서인 경우 그대로 반환합니다.

#### 2. 메모리 공유 동작

- **torch.from_numpy**:
  - **항상** NumPy 배열과 메모리를 공유합니다.
  - 원본 NumPy 배열이 변경되면 텐서도 변경되고, 반대의 경우도 마찬가지입니다.

- **torch.as_tensor**:
  - NumPy 배열인 경우 가능하면 메모리를 공유합니다.
  - 파이썬 리스트 등 다른 데이터 유형의 경우 새로운 메모리를 할당합니다.
  - `device` 파라미터를 사용하여 GPU로 데이터를 이동할 경우 메모리 공유가 불가능합니다.

#### 3. 사용 유연성

- **torch.from_numpy**:
  - NumPy 배열의 데이터 타입만 지원합니다.
  - `dtype` 변환 파라미터가 없습니다.

- **torch.as_tensor**:
  - `dtype`, `device` 파라미터를 사용하여 데이터 타입과 저장 장치를 지정할 수 있습니다.
  - 더 유연한 변환 옵션을 제공합니다.

### 사용 예시

```python
import numpy as np
import torch

# NumPy 배열 생성
np_array = np.array([1, 2, 3, 4, 5])

# torch.from_numpy 사용
tensor_from_numpy = torch.from_numpy(np_array)

# torch.as_tensor 사용
tensor_as_tensor = torch.as_tensor(np_array)
tensor_as_tensor_float = torch.as_tensor(np_array, dtype=torch.float32)

# 메모리 공유 테스트
np_array[0] = 100
print(f"변경된 NumPy 배열: {np_array}")
print(f"from_numpy 텐서: {tensor_from_numpy}")  # 변경됨
print(f"as_tensor 텐서: {tensor_as_tensor}")    # 변경됨
```


### 언제 어떤 함수를 사용해야 할까요?

- **torch.from_numpy**: NumPy 배열과 PyTorch 텐서 간에 명시적인 메모리 공유가 필요할 때 사용합니다.

- **torch.as_tensor**:
  - 다양한 입력 데이터 유형을 처리해야 할 때
  - 데이터 타입이나 장치(CPU/GPU)를 변환해야 할 때
  - 일반적으로 더 유연하므로 대부분의 경우에 권장됩니다.

- **torch.tensor**: 데이터의 복사본을 만들고 원본 데이터와 연결을 끊고 싶을 때 사용합니다(참고로 언급).

### 주의사항

메모리를 공유하는 경우, 원본 데이터를 변경하면 텐서도 변경됩니다. 이것은 성능 이점이 있지만 의도치 않은 결과를 초래할 수도 있으므로 주의해야 합니다.

In [12]:
numpy_array = np.array([1, 2, 3])
a = torch.from_numpy(numpy_array)
a

tensor([1, 2, 3])

In [13]:
b = torch.as_tensor(numpy_array)
b

tensor([1, 2, 3])

In [14]:
numpy_array[0] = numpy_array[0] * 10
print("numpy_array:", numpy_array)
print("a:", a)
print("b:", b)

numpy_array: [10  2  3]
a: tensor([10,  2,  3])
b: tensor([10,  2,  3])


## torch.tensor()와 torch.Tensor() 비교

`torch.tensor()`와 `torch.Tensor()`는 이름이 비슷하여 혼동하기 쉽지만, 목적과 동작 방식에 중요한 차이가 있습니다. 두 함수의 공통점과 차이점을 자세히 살펴보겠습니다.

### 공통점

1. **PyTorch 텐서 생성**: 두 함수 모두 PyTorch 텐서를 생성합니다.
2. **다차원 데이터 처리**: 다차원 데이터를 처리할 수 있습니다.
3. **GPU 연산 지원**: 생성된 텐서는 GPU로 이동하여 연산 가속화가 가능합니다.

### 차이점

#### 1. 함수 vs 클래스

- **torch.tensor()**:
  - **함수(function)** 입니다.
  - 데이터로부터 텐서를 생성하는 권장되는 방법입니다.

- **torch.Tensor()**:
  - **클래스 생성자(class constructor)** 입니다.
  - `torch.FloatTensor`의 별칭으로, 항상 float32 데이터 타입의 텐서를 생성합니다.

#### 2. 데이터 타입 처리

- **torch.tensor()**:
  - 데이터 타입을 자동으로 유추하거나 `dtype` 매개변수로 명시적으로 지정할 수 있습니다.
  - 입력 데이터에 따라 적절한 데이터 타입을 결정합니다.
  - 예: 정수 리스트는 기본적으로 int64 텐서가 됩니다.

- **torch.Tensor()**:
  - **항상** float32(torch.float) 데이터 타입의 텐서를 생성합니다.
  - 다른 데이터 타입을 원할 경우 별도의 형변환이 필요합니다.

#### 3. 초기화 방식

- **torch.tensor()**:
  - 주어진 데이터로 텐서를 초기화합니다.
  - 데이터 없이는 호출할 수 없습니다.
```python
x = torch.tensor([1, 2, 3])  # 데이터로 초기화
```


- **torch.Tensor()**:
  - 크기(shape)를 지정하여 **비초기화된(uninitialized)** 텐서를 생성할 수 있습니다.
  - 이 경우 메모리에 있던 값들이 그대로 남아있어 임의의 값을 가집니다.
```python
x = torch.Tensor(3, 4)  # 3x4 크기의 비초기화 텐서
```


#### 4. 추론 및 일관성

- **torch.tensor()**:
  - 입력 데이터의 타입을 보존하거나 명시적으로 변환할 수 있어 더 예측 가능합니다.
  - PyTorch 1.0 이후 도입된 함수로, NumPy 스타일의 API를 따릅니다.

- **torch.Tensor()**:
  - 데이터 타입이 항상 float32로 고정되어 일관성이 떨어질 수 있습니다.
  - 레거시 API에 가깝습니다.

### 사용 예시

```python
import torch

# torch.tensor() 사용 예시
data = [1, 2, 3]
t1 = torch.tensor(data)  # 기본적으로 int64 텐서
t2 = torch.tensor(data, dtype=torch.float32)  # 명시적으로 float32 지정
t3 = torch.tensor([[1, 2], [3, 4]])  # 2D 텐서

print(f"t1: {t1}, dtype: {t1.dtype}")
print(f"t2: {t2}, dtype: {t2.dtype}")
print(f"t3: {t3}, dtype: {t3.dtype}")

# torch.Tensor() 사용 예시
t4 = torch.Tensor([1, 2, 3])  # 항상 float32 텐서
t5 = torch.Tensor(2, 3)  # 2x3 크기의 비초기화된 텐서

print(f"t4: {t4}, dtype: {t4.dtype}")
print(f"t5: {t5}, dtype: {t5.dtype}")  # 임의의 값 포함

# 데이터 타입 차이 확인
int_list = [1, 2, 3]
t6 = torch.tensor(int_list)  # int64
t7 = torch.Tensor(int_list)  # float32

print(f"t6: {t6}, dtype: {t6.dtype}")
print(f"t7: {t7}, dtype: {t7.dtype}")
```


### 권장 사용법

- **torch.tensor()** 사용을 권장
  - 더 명확하고 예측 가능한 동작
  - 데이터 타입을 명시적으로 제어 가능
  - 최신 PyTorch 스타일에 부합

- **torch.Tensor()** 사용을 피해야 하는 경우
  - 데이터 타입이 중요한 경우
  - 비초기화된 메모리를 사용하면 위험한 경우
  - 정확한 데이터 타입 제어가 필요한 경우

### 대안 함수

텐서 생성을 위한 더 특화된 함수들,
- `torch.zeros()`: 0으로 채워진 텐서
- `torch.ones()`: 1로 채워진 텐서
- `torch.rand()`: 0과 1 사이의 균등 분포 난수로 채워진 텐서
- `torch.randn()`: 표준 정규 분포 난수로 채워진 텐서

이러한 함수들은 목적에 맞게 텐서를 초기화하므로 `torch.Tensor()`보다 안전하고 명확합니다.

In [15]:
data = [1, 2, 3, 4, 5]
tensor1 = torch.tensor(data)
print("torch.tensor:", tensor1)
print("torch.tensor 의 dtype:", tensor1.dtype)

torch.tensor: tensor([1, 2, 3, 4, 5])
torch.tensor 의 dtype: torch.int64


In [16]:
tensor2 = torch.Tensor(data)
print("torch.Tensor", tensor2)
print("torch.Tensor 의 dtype:", tensor2.dtype)

torch.Tensor tensor([1., 2., 3., 4., 5.])
torch.Tensor 의 dtype: torch.float32


In [17]:
dim2_tensor = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
dim2_tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
simple_index = torch.tensor([0, 1])
# 열을 기준으로 simple_index 에 있는 0, 2 에 해당하는 값 뽑기.
# index 는 Torch type 이어야함
torch.index_select(dim2_tensor, dim=1, index=simple_index)

tensor([[ 0,  1],
        [10, 11]])

In [25]:
mask = dim2_tensor >= 5
dim2_tensor[mask]

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
torch.masked_select(dim2_tensor, mask)

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### PyTorch의 `torch.take()` 함수
`torch.take()` 함수는 PyTorch에서 텐서의 특정 인덱스에 위치한 요소들을 선택하여 새로운 1차원 텐서로 반환하는 함수입니다. 이 함수에 대해 자세히 설명해 드리겠습니다.

**기본 문법**

``` python
torch.take(input, index)
```
- **input**: 값을 추출할 원본 텐서
- **index**: 추출할 요소들의 인덱스를 담은 텐서

**주요 특징**

1. 평탄화(Flattening) 후 인덱싱
    - `torch.take()`는 우선 입력 텐서를 1차원으로 평탄화합니다.
    - 그 후 인덱스 텐서의 값에 따라 요소를 선택합니다.

2. 항상 1차원 출력
    - 결과는 항상 1차원 텐서로 반환됩니다.
    - 출력 텐서의 크기는 인덱스 텐서의 크기와 동일합니다.

3. 다차원 텐서 처리
    - 다차원 텐서에서도 사용 가능하며, 이 경우 텐서를 먼저 평탄화합니다.


In [27]:
# Tensor 가 1차원으로 바뀌었을 때를 기준으로 index 접근 결과
torch.take(dim2_tensor, index=torch.tensor([10, 13]))

tensor([10, 13])

### PyTorch의 `torch.gather()` 함수

- `torch.gather()`는 PyTorch에서 특정 차원을 따라 지정된 인덱스에 있는 값을 수집하는 강력한 함수입니다.
- 복잡한 인덱싱 작업을 수행할 때 특히 유용합니다.

#### 기본 문법

```python
torch.gather(input, dim, index, *, sparse_grad=False, out=None)
```

- **input**: 값을 수집할 원본 텐서
- **dim**: 수집할 차원 (축)
- **index**: 수집할 인덱스가 포함된 텐서 (input과 같은 차원을 가져야 함)
- **sparse_grad**: 희소 그래디언트를 사용할지 여부 (기본값: False)
- **out**: 출력 텐서 (선택 사항)

#### 주요 특징

1. **차원 선택적 수집**
   - 특정 차원을 따라 값을 수집합니다.
   - 다른 텐서 연산과 달리 차원을 지정하여 작동합니다.

2. **인덱스 기반 수집**
   - `index` 텐서의 값은 `input` 텐서에서 선택할 인덱스를 지정합니다.
   - `index` 텐서의 모양은 `input` 텐서와 같아야 합니다(수집 차원 제외).

3. **출력 형태**
   - 출력 텐서의 모양은 `index` 텐서의 모양과 동일합니다.

#### 작동 방식 설명

`gather` 함수를 이해하기 위한 간단한 규칙

1. `dim=0`일 때: 각 열에서 지정된 행 인덱스의 값을 가져옵니다.
2. `dim=1`일 때: 각 행에서 지정된 열 인덱스의 값을 가져옵니다.

#### 예제 코드

##### 예제 1: 1차원 텐서에서 gather 사용

```python
import torch

# 1차원 텐서
src = torch.tensor([1, 2, 3, 4, 5])
indices = torch.tensor([0, 4, 2])

# dim=0에서 gather
result = torch.gather(src, dim=0, index=indices)
print(result)  # tensor([1, 5, 3])
```


##### 예제 2: 2차원 텐서에서 gather 사용 (dim=0)

```python
import torch

# 2차원 텐서
src = torch.tensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# dim=0에서 gather (행 방향)
indices = torch.tensor([[0, 1, 2],
                        [2, 0, 1]])
result = torch.gather(src, dim=0, index=indices)
print(result)
# 출력:
# tensor([[1, 5, 9],
#         [7, 2, 6]])
```


이 예제에서,
- 첫 번째 행의 경우: 첫 번째 열에서 인덱스 0의 값(1), 두 번째 열에서 인덱스 1의 값(5), 세 번째 열에서 인덱스 2의 값(9)을 가져옵니다.
- 두 번째 행의 경우: 첫 번째 열에서 인덱스 2의 값(7), 두 번째 열에서 인덱스 0의 값(2), 세 번째 열에서 인덱스 1의 값(6)을 가져옵니다.

##### 예제 3: 2차원 텐서에서 gather 사용 (dim=1)

```python
import torch

# 2차원 텐서
src = torch.tensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# dim=1에서 gather (열 방향)
indices = torch.tensor([[0, 0, 0],
                        [1, 1, 1],
                        [2, 2, 2]])
result = torch.gather(src, dim=1, index=indices)
print(result)
# 출력:
# tensor([[1, 1, 1],
#         [5, 5, 5],
#         [9, 9, 9]])
```


이 예제에서,
- 첫 번째 행에서는 인덱스 0, 0, 0에 해당하는 값들(1, 1, 1)을 가져옵니다.
- 두 번째 행에서는 인덱스 1, 1, 1에 해당하는 값들(5, 5, 5)을 가져옵니다.
- 세 번째 행에서는 인덱스 2, 2, 2에 해당하는 값들(9, 9, 9)을 가져옵니다.

#### 실용적인 활용 사례

1. **자연어 처리**
   - 단어 임베딩에서 특정 단어의 벡터를 추출할 때 사용합니다.

2. **강화학습**
   - 선택된 액션에 대한 Q-값을 추출할 때 사용합니다.

3. **이미지 처리**
   - 특정 픽셀 위치의 값을 추출할 때 유용합니다.

4. **모델 앙상블**
   - 여러 모델의 예측 중에서 특정 예측을 선택할 때 사용합니다.

#### 주의사항

1. `index` 텐서의 값은 `input` 텐서의 해당 차원의 유효한 인덱스여야 합니다.
2. `index` 텐서의 모양은 `input` 텐서와 동일해야 하지만, 수집하는 차원은 예외입니다.
3. `gather`는 복잡한 인덱싱을 필요로 하는 상황에서 매우 유용하지만, 기본적인 인덱싱으로 해결할 수 있는 경우에는 일반 인덱싱이 더 간단할 수 있습니다.

`torch.gather()`는 특히 특정 차원을 따라 복잡한 인덱싱이 필요한 딥러닝 모델에서 매우 유용한 함수입니다.

In [28]:
recon_index = torch.tensor([[0, 1], [9, 8]])
torch.gather(dim2_tensor, dim=1, index=recon_index)

tensor([[ 0,  1],
        [19, 18]])

## tensor 의 shape 변경

In [31]:
simple_tensor = torch.randn(2, 3, 5)
simple_tensor.size()

torch.Size([2, 3, 5])

In [32]:
simple_tensor.shape

torch.Size([2, 3, 5])

In [34]:
simple_tensor.reshape(5, 6)

tensor([[-1.0262,  0.5795, -0.2417, -2.2712, -1.1255,  0.4322],
        [-0.3670, -0.7418, -0.7314, -1.0039,  1.2778,  0.6524],
        [ 0.2534,  0.7632,  0.4161,  1.4552, -0.6906,  0.4433],
        [ 2.0080,  1.3097, -0.0367, -0.8507, -0.4812, -0.7044],
        [-1.0369, -1.5068,  0.8195,  1.0110,  0.4235,  1.3872]])

In [37]:
simple_tensor.reshape(3, -1).size()

torch.Size([3, 10])

In [38]:
simple_tensor.view(5, 6)

tensor([[-1.0262,  0.5795, -0.2417, -2.2712, -1.1255,  0.4322],
        [-0.3670, -0.7418, -0.7314, -1.0039,  1.2778,  0.6524],
        [ 0.2534,  0.7632,  0.4161,  1.4552, -0.6906,  0.4433],
        [ 2.0080,  1.3097, -0.0367, -0.8507, -0.4812, -0.7044],
        [-1.0369, -1.5068,  0.8195,  1.0110,  0.4235,  1.3872]])

In [39]:
simple_tensor.view(3, -1).size()

torch.Size([3, 10])


### PyTorch의 Tensor.reshape와 Tensor.view의 공통점과 차이점

#### 공통점

1. **기능적 목적**: 두 메서드 모두 텐서의 모양을 변경하는 데 사용됩니다.
2. **원소 개수 유지**: 두 메서드 모두 텐서의 총 원소 개수를 유지해야 합니다 (변경된 형태의 차원 곱이 원래 텐서의 원소 개수와 같아야 함).
3. **메모리 효율성**: 가능한 경우 두 메서드 모두 새로운 메모리를 할당하지 않고 원본 데이터를 재해석합니다.

#### 차이점

1. **연속성(Contiguity) 처리**
   - `view()`: 오직 연속적인(contiguous) 텐서에서만 작동합니다. 텐서가 연속적이지 않으면 오류가 발생합니다.
   - `reshape()`: 연속적 및 비연속적 텐서 모두에서 작동합니다. 내부적으로 비연속적 텐서를 처리합니다.

2. **복사 동작**
   - `view()`: 항상 원본 데이터를 공유하는 새로운 뷰를 반환하며, 메모리 복사가 발생하지 않습니다.
   - `reshape()`: 가능하면 view를 반환하지만, 필요한 경우(예: 비연속 텐서) 데이터를 연속적인 텐서로 복사한 후 뷰를 반환합니다.

3. **메모리 레이아웃**
   - `view()`: 원본 텐서의 메모리 레이아웃이 변경되지 않습니다.
   - `reshape()`: 필요한 경우 내부적으로 데이터를 재정렬하여 요청된 형태를 만들 수 있습니다.

#### 실용적인 사용 가이드

- **`view()` 사용 시기**: 텐서가 연속적이라고 확신할 때, 메모리 복사를 피하고 싶을 때 사용합니다.
- **`reshape()` 사용 시기**: 텐서의 연속성에 확신이 없거나, 더 안전한 옵션이 필요할 때 사용합니다. 일반적으로 더 안전한 선택입니다.

#### 주의사항

- 두 메서드 모두 차원을 교환(swap)하는 데는 적합하지 않습니다. 차원 교환에는 `permute()` 또는 `transpose()`를 사용하는 것이 적절합니다.
- 텐서가 변경되면 `view()`로 생성된 텐서도 영향을 받지만, `reshape()`가 복사를 수행한 경우에는 영향을 받지 않을 수 있습니다.